### ISSUE TITLE
shouldn't MidiPortSelector unregister itself from the MidiManager ?

### ISSUE THREAD

**Issue by loki666** [philburk/android-midisuite#18]

**Comment by philburk** [comment]
MidiPortSelector calls registerDeviceCallback() in the constructor. But it never calls **un**registerDeviceCallback(). 

The callback will be unregistered automatically when the app closes. Do you need an explicit call to make it unregister? Or were you just worried that there would be a leak of some sort?

**Comment by philburk** [comment]
Good point. Is the Activity being recreated because of screen rotation?

There was a bug in Marshmallow that prevented unregisterDeviceCallback() from working. But it was fixed for N. I will look at adding a method to unregister the callback in MidiPortSelector so we can call it when the Activity is destroyed.

Thanks for reporting this.

**Comment by loki666** [comment]
Yes the Activity is being recreated because of screen rotation.

**Comment by loki666** [comment]
Any news on this ?

**Comment by philburk** [comment]
I have a PullRequest with a fix for this issue here:

    https://github.com/philburk/android-midisuite/pull/19

Feedback appreciated.

**Comment by loki666** [comment]
seems to works here, no more multiple callbacks
