### ISSUE TITLE
Using phone as a Midi Bluetooth bridge ,?

### ISSUE THREAD

**Issue by Mylab6** [philburk/android-midisuite#70]
Hi, is it possible to use this in order to say attach a USB midi keyboard to my Android phone and via Bluetooth connect to my iPad. 

Ideally I'd then be able to play the keyboard and send midi data to my iPad.

**Comment by philburk** [comment]
Unfortunately no. I tried pairing a Pixel phone and an IPad using BLE-MIDI. They would not connect.

I believe this is because both devices are trying to act as **hosts**. You need one device to act as a **peripheral**, eg. a keyboard.

There are devices such as the Yamaha UD-BT01 that may do what you want.
https://usa.yamaha.com/products/musical_instruments/pianos/accessories/ud-bt01/index.html

**Comment by Mylab6** [comment]
Thanks, I have my own solution here . 

https://github.com/Mylab6/PiBluetoothMidSetup
